project:
  type: website
  render:
    - "*.qmd"
    - "!classic/"
  resources:
    - classic
website:
  title: "Bo Yang Tang"
  navbar:
    right:
      - about.qmd
format:
  html:
    theme:
      - slate
      - brand
    css: styles.css



